---
title: "JO Test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#test

library(dplyr)

# set working directory to where you stored the .csv file
#setwd("/Users/juliaolsen/Desktop/Fall 2021/BST 260/BST260FinalProject")

t1 <- read.csv("data1.csv")

# Determine which duplicates will be the best to keep 
unique(t1$COU)
unique(t1$Country) #keep
unique(t1$IND) #keep
unique(t1$Indicator) #keep
unique(t1$SEX) 
unique(t1$Sex) #keep
unique(t1$AGE)
unique(t1$Age.Group) #keep
unique(t1$TIME)
unique(t1$Time) #keep
unique(t1$Unit.Code)
unique(t1$Unit) #keep
unique(t1$PowerCode.Code)
unique(t1$PowerCode)
unique(t1$Reference.Period.Code)
unique(t1$Reference.Period)
unique(t1$Flag.Codes)
unique(t1$Flags) #keep

t1 <- t1 %>% 
    select(Country, IND, Indicator, Sex, Age.Group, Time, Value, Unit, Flags)
```

To filter *only* OECD countries:
    ```{r}
OECD_label <- c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", "Costa Rica", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway", "Poland", "Portugal", "Slovak Republic", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "United Kingdom", "United States")

t1 <- t1 %>%
    filter (Country %in% OECD_label) %>%
    mutate(Time=as.integer(Time), Value=as.numeric(Value))

head(t1)
str(t1)
```
```{r}
#creating dataframe with only 'Labour force participation rate, by sex and age group' indicator
t2 <- t1 %>%
    filter(Indicator %in% c('Labour force participation rate, by sex and age group ', 'Share of employed who are managers, by sex', 'Female share of seats on boards of the largest publicly listed companies', 'Female share of seats in national parliaments'))
head(t2)
t2

```

Wrangling data for scatterplot:
    
    ```{r}
library(tidyr)

female_labour_force_participation <- t2 %>%
  filter(Indicator == 'Labour force participation rate, by sex and age group ' & Sex == "Women" & Age.Group=="Total") %>%
  select(Country, Value, Time) %>%
  rename(female_labour_force_participation = Value)

female_share_boards <- t2 %>%
  filter(Indicator == 'Female share of seats on boards of the largest publicly listed companies' & Sex == "Women" & Age.Group=="Total") %>%
  select(Country, Value, Time) %>%
  rename(female_share_boards = Value)

female_share_parliament <- t2 %>%
  filter(Indicator == 'Female share of seats in national parliaments' & Sex == "Women" & Age.Group=="Total") %>%
  select(Country, Value, Time) %>%
  rename(female_share_parliament = Value)

female_share_managers <- t2 %>%
  filter(Indicator == 'Share of employed who are managers, by sex' & Sex == "Women" & Age.Group=="Total") %>%
  select(Country, Value, Time) %>%
  rename(female_share_managers = Value)

# Create new dataframe
data_list <- list(female_labour_force_participation, female_share_boards, female_share_parliament, female_share_managers)

t3 <- data_list %>% 
  reduce(left_join, by=c("Country", "Time"))
t3

```

#Shiny App

```{r}
#load packages
library(shiny)
library(tidyverse)
library(forcats)
library(dslabs)

shinyApp(
  # Define UI for application
ui <- fluidPage(
  # Change theme to darkly
  theme = shinythemes::shinytheme("darkly"),
  # Application title
  titlePanel("Labor Force Statistics and Leadership Positions by Gender"),
  
  tabsetPanel(
    tabPanel("Line Plot",
             # Dropdown menu that allows the user to choose a country for the line plot
             selectInput(inputId = "country", label = "Choose a country:",
                        choices = c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", "Costa Rica", "Czech
                                    Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary",
                                    "Iceland", "Ireland", "Israel", "Italy", "Japan", "Korea", "Latvia", "Lithuania",
                                    "Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway", "Poland", "Portugal",
                                    "Slovak Republic", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey",                                                   "United States"), selected = NULL, multiple = FALSE),
             selectInput(inputId = "age", label = "Choose an Age Group:",
                        choices = c("15-24","25-54","55-64","Total"), selected = NULL, multiple = FALSE),
             # Show a plot of the generated plot
             mainPanel(
               plotOutput("LinePlot")
             )
    ),
    tabPanel("Scatterplot",
            # selectInput(inputId = "variable", label = "Choose a Variable:",
             #           choices = c('Share of female managers', 'Female share of seats on boards of the largest publicly listed companies', 'Female share of seats in national parliaments'), selected = NULL, multiple = FALSE),
             sliderInput(inputId = "year", "Year:",
                         min = 1970, max = 2021,
                         value = 2000, 
                         step = 1, #slider increases by 1
                         sep = "",       # keep years in year format and not 1,960 format
                         ticks = FALSE,  # don't show tick marks on slider bar
                         animate = TRUE), # add play button to animate
             # Show a plot of the generated plot
             mainPanel(
               plotOutput("Scatterplot")
             )
    )
  )
),

# Define server logic
server <- function(input, output) {
  output$LinePlot <- renderPlot({
    t2 %>% 
      filter(Country %in% input$country & Indicator %in% c('Labour force participation rate, by sex and age group ') & Age.Group %in% input$age & !is.na(Value)) %>%
      ggplot(aes(x=Time, y=Value, color=Sex)) + 
      geom_line() + 
      scale_x_continuous(breaks = seq(1970, 2021, 5), limits = c(1970, 2021)) +
      scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
      xlab("Year") +
      ylab("Labor Force Participation Rate(%)") +
      ggtitle(paste("Labor Force Participation Rate by Sex from 1970 to 2021 in", input$country))
  })
  output$Scatterplot <- renderPlot({
    t3 %>% 
      filter(Time %in% input$year) %>%
      ggplot(aes(female_labour_force_participation, female_share_boards, color=Country)) + 
      geom_point() + 
      #scale_y_continuous(breaks = seq(0.5, 9.5, 0.5), limits = c(0.5, 9.5)) +
      #scale_x_continuous(breaks = seq(15, 85, 5), limits = c(15, 85)) +
      xlab("Female Labor Force Participation Rate(%)") +
      ylab(female_share_boards) +
      ggtitle(paste("female_share_boards against Female Labor Force Participation Rate in", input$year))
  })
}
  
  
  
  
)
```

