---
title: "Read In Data"
output: html_document
---

```{r}
library(dplyr)

# set working directory to where you stored the .csv file
setwd("/Users/sarahchristensen/Documents/Harvard/Fall2021/BST260/BST260FinalProject") 

ALLCOUNTRY <- read.csv("data1.csv")

# Determine which duplicates will be the best to keep 
unique(ALLCOUNTRY$COU)
unique(ALLCOUNTRY$Country) #keep
unique(ALLCOUNTRY$IND) #keep
unique(ALLCOUNTRY$Indicator) #keep
unique(ALLCOUNTRY$SEX) 
unique(ALLCOUNTRY$Sex) #keep
unique(ALLCOUNTRY$AGE)
unique(ALLCOUNTRY$Age.Group) #keep
unique(ALLCOUNTRY$TIME)
unique(ALLCOUNTRY$Time) #keep
unique(ALLCOUNTRY$Unit.Code)
unique(ALLCOUNTRY$Unit) #keep
unique(ALLCOUNTRY$PowerCode.Code)
unique(ALLCOUNTRY$PowerCode)
unique(ALLCOUNTRY$Reference.Period.Code)
unique(ALLCOUNTRY$Reference.Period)
unique(ALLCOUNTRY$Flag.Codes)
unique(ALLCOUNTRY$Flags) #keep

ALLCOUNTRY <- ALLCOUNTRY %>% 
  select(Country, IND, Indicator, Sex, Age.Group, Time, Value, Unit, Flags)
```

To filter *only* OECD countries:
```{r}
OECD_label <- c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", "Costa Rica", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway", "Poland", "Portugal", "Slovak Republic", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "United Kingdom", "United States")

t1 <- ALLCOUNTRY %>%
  filter (Country %in% OECD_label)
```

Creating a variable for proportion of time spent in unpaid work (minutes per day) / time spent in total work (minutes per day):

```{r}
library(tidyr)

# Isolate variables of interest
unpaid_time <- t1 %>%
  filter(Indicator == "Time spent in unpaid work, by sex") %>%
  select(Country, Sex, Age.Group, Time, Value) %>%
  rename(unpaid_time = Value)

total_time <- t1 %>%
  filter(Indicator == "Time spent in total work, by sex") %>%
  select(Country, Sex, Age.Group, Time, Value) %>%
  rename(total_time = Value)

# Create new dataframe
new_data <- merge(unpaid_time, total_time, by=c("Country", "Sex", "Age.Group", "Time"))

# Create ratio variable
new_data <- new_data %>%
  mutate(prop_unpaid = unpaid_time/total_time)
```